### PR TITLE
Added sessionize method

### PR DESCRIPTION
**Pull request by koaning**
I'm just trying out stuff here.

### CODE REVIEW

**Comment by koaning** [comment]
@ritchie46 I've started on an initial commit. It's not set in stone, as mentioned before, but I figured on what your preference might be. 

We could make it work like; 

```python
from valve.pandas import sessionize as sess_pd
from valve.polars import sessionize as sess_pl
```

This could work, but I'm wondering if maybe a multiple-dispatch trick could work such that you could also do; 

```python
from valve import sessionize

# Both of these lines would work. 
pd.DataFrame(...).pipe(sessionize)
pl.DataFrame(...).pipe(sessionize)
```

I'm leaning towards implementing both, any preferences?

**Comment by ritchie46** [comment]
I think that implementing the first is easiest maintainable. E.g. a separate implementations for `pandas` / `polars`.

the latter `from valve import sessionize` could then be a thin wrapper that simply checks a type and dispatches to the specialized functions.

**Comment by ritchie46** [comment]
Feel free to merge btw. :+1:

**Comment by koaning** [comment]
Will do.

**Pull request merged**
